"""Initial Migration

Revision ID: f8d93c5bd425
Revises: 8241d9dd064d
Create Date: 2025-12-28 10:41:06.471560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d93c5bd425'
down_revision: Union[str, Sequence[str], None] = '8241d9dd064d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_student', sa.Boolean(), nullable=True),
    sa.Column('knowledge_level', sa.Enum('beginner', 'intermediate', 'advanced', name='levelenum'), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='genderenum'), nullable=False),
    sa.Column('russian_level', sa.Enum('beginner', 'intermediate', 'advanced', name='levelenum'), nullable=True),
    sa.Column('russian_level_voice_path', sa.String(length=255), nullable=True),
    sa.Column('english_level', sa.Enum('beginner', 'intermediate', 'advanced', name='levelenum'), nullable=True),
    sa.Column('english_level_voice_path', sa.String(length=255), nullable=True),
    sa.Column('ielts_certificate_path', sa.String(length=255), nullable=True),
    sa.Column('work_experience', sa.String(length=255), nullable=True),
    sa.Column('last_workplace', sa.String(length=255), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('resume_path', sa.String(length=255), nullable=True),
    sa.Column('how_find_out', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
